[project]
name = 'Tokenized-Construction-Quantum-Architecture'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.architect-verification]
path = 'contracts/architect-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.construction-coordination]
path = 'contracts/construction-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
